---
title: O operando 'Throw' deve ser derivado de 'System.Exception'
ms.date: 07/20/2015
f1_keywords:
- vbc30665
- bc30665
helpviewer_keywords:
- BC30665
ms.assetid: 7c228087-39ea-4b30-a410-6ba711e67e5e
ms.openlocfilehash: e9e43605d5b3a752e4024414eeb87dea60d118b3
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 09/23/2020
ms.locfileid: "91068902"
---
# <a name="throw-operand-must-derive-from-systemexception"></a>O operando 'Throw' deve ser derivado de 'System.Exception'

O argumento fornecido `Throw` deve ser uma instância do `System.Exception` ou uma instância de uma classe derivada de `System.Exception` .  
  
 **ID do erro:** BC30665  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
- Use um argumento derivado de `System.Exception` , como no exemplo a seguir.  
  
    ```vb
    Throw New System.Exception("This is an error.")  
    ```  
  
## <a name="see-also"></a>Confira também

- [Instrução Throw](../language-reference/statements/throw-statement.md)
- [Instrução Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [Tratando e gerando exceções no .NET](../../standard/exceptions/index.md)
