---
title: '&#39;Exit Try&#39; só pode aparecer dentro de um &#39;tente&#39; instrução'
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: a33f5750a0ba8f833e623101467327635bf0c8d8
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 05/04/2018
ms.locfileid: "33614476"
---
# <a name="39exit-try39-can-only-appear-inside-a-39try39-statement"></a>&#39;Exit Try&#39; só pode aparecer dentro de um &#39;tente&#39; instrução
`Exit Try` só pode aparecer dentro de uma `Try` bloco de instrução. Ou você tem uma redundância `Exit Try` instrução, ou seu `Exit Try` instrução aparece fora dos limites do correspondente `Try` bloco.  
  
 **ID do erro:** BC30393  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
1.  Localize e remova o desnecessária `Exit Try` instrução.  
  
2.  Mover o `Exit Try` instrução até o local apropriado no seu código.  
  
## <a name="see-also"></a>Consulte também  
 [Instrução Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
