---
title: Bloco 'Catch' nunca alcançado; &lt;exceção&gt; manipulado acima na mesma instrução 'Try'
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 37fe7ec852f191c249c59561d2e1f30a6efbb50a
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 12/22/2018
ms.locfileid: "53775142"
---
# <a name="catch-block-never-reached-ltexceptiongt-handled-above-in-the-same-try-statement"></a>Bloco 'Catch' nunca alcançado; &lt;exceção&gt; manipulado acima na mesma instrução 'Try'
Um `Catch` bloco no código não pode ser acessado porque ela é tratada em precedidos `Try` bloco.  
  
 Por padrão, esta mensagem é um aviso. Para obter mais informações sobre como ocultar avisos ou tratar avisos como erros, consulte [Configurando avisos no Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)  
  
 **ID do erro:** BC42031  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
-   Remova a instrução redundante.  
  
## <a name="see-also"></a>Consulte também  
 [Como: Capturar uma exceção no Visual Basic](https://msdn.microsoft.com/library/f3063c89-d2bf-49b1-91b5-b87edfb18b95)  
 [Como: Testar o código com um bloco Try... Bloco Catch no Visual Basic](https://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Como: Erros de filtro em um bloco Catch no Visual Basic](https://msdn.microsoft.com/library/85964d0a-56e7-4301-a96e-5eaea23b7b9b)  
 [Passo a passo: (Visual Basic) de tratamento de exceções estruturado](https://msdn.microsoft.com/library/440da655-4b32-490b-8b16-bfe46f41fa76)  
 [Instrução Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
